### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by hijonathan** [webpro/DOMtastic#28]
Seems like there's more to it than just making `classList` work: https://saucelabs.com/tests/2a7a38c75df246158fccca6e56b21e11

I have the classList patch on a branch but want to get your thoughts on actually supporting IE9. It sounds like it shouldn't be that bad.

**Comment by webpro** [comment]
DOMtastic is for modern browsers. If you need support for IE9 you can use a classList polyfill. And indeed, you need to stay away from specific DOM manipulation within `<table>` and `<select>` elements.

I'd rather not include major workarounds for old browsers.

**Comment by hijonathan** [comment]
Fair enough.
