### ISSUE TITLE
width/height support

### ISSUE THREAD

**Issue by futurist** [webpro/DOMtastic#32]
I'm start using DOMtastic but found my previous code have many .width()/.height, so is there any way to add these?
or, think, the way get w/ margin w/o margin, w/padding+border, w/o padding+border, etc
maybe plugins?

**Comment by webpro** [comment]
You can use a plugin indeed. Here's a simple example:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="domtastic.min.js"></script>
        <script>
            $.fn.rect = function() {
                return this[0].getBoundingClientRect();
            }
        </script>
    </head>
    <body>
        <script>
            console.log($('body').rect());
        </script>
    </body>
</html>
```

Let me know if it works for you.
