### ISSUE TITLE
Documentation examples for multiple css() and attr() broken

### ISSUE THREAD

**Issue by daviestar** [webpro/DOMtastic#33]
The example for adding multiple `attr` is broken:
```javascript
$('.item').attr({'attr1', 'value1'}, {'attr2', 'value2});
```
http://domtastic.js.org/doc/#dom/attr

Could be:
```javascript
$('img').attr({
    width: 100,
    height: 100
});
```

The example for adding multiple `css` is similar:
```javascript
$('.item').css({'border-width', '1px'}, {'display', 'inline-block});
```
http://domtastic.js.org/doc/#css

Could be:
```javascript
$('div').css({
    width: 100+'px',
    height: 100+'px'
});
```

Been using DOMTastic a lot recently and it's been great.  Thanks guys.

If I had one feature request it would be Jquery's `one` helper.

**Comment by webpro** [comment]
Thanks @daviestar! I was also inspired to add the `one` method, it'll be released shortly in the next minor version.

**Comment by daviestar** [comment]
Thanks @webpro, look forward to checking it out!

**Comment by webpro** [comment]
`one` is already in [0.12.0](https://github.com/webpro/DOMtastic/releases/tag/0.12.0)
