### ISSUE TITLE
Custom build '--include' not working

### ISSUE THREAD

**Issue by olsonpm** [webpro/DOMtastic#37]
DOMtastic version 0.12.1
using the script: `npm run bundle -- --include=selector,array,event`

results in a file that doesn't export a selector properly.  It seems something is going wrong with the rollup import transforms because eslint reports 'selector' being not defined in the following section:

```js
// - the following 'selector' variables are not defined

// line 448
if (typeof selector !== 'undefined') {
  $ = selector.$;
  $.matches = selector.matches;
  api.find = selector.find;
}
```

It seems that `selector.$` from above is supposed to be the exported `$` from `selector/index.js`, which in the output should be `$$2`

```js
// line 107
var $$2 = function (selector) {
  var context = arguments.length <= 1 || arguments[1] === undefined ? document : arguments[1];
// ...
```

I have only read about rollup and am new to webpack/babel so I don't want to spend much more time looking further into the issue in case you had any insight.

The library seems great - I'll use the full version in the meantime.

**Comment by jimasun** [comment]
Same issue. It seems that whatever I choose to exclude, the only two modules are @module Util and @module Ready.

**Comment by webpro** [comment]
Sorry @olsonpm and @jimasun.

The issue is that I've moved modules to folders, and that structure should be followed when including or excluding modules in a custom build. I see @jimasun has found this himself already.

To see the all module names, you can run:

```
> npm run bundle -- --include=index

Excluded modules: array, baseClass, css, dom/attr, dom/class, dom/contains, dom/data, dom/extra, dom/html, dom/index, event/index, event/ready, event/trigger, noconflict, selector/closest, selector/extra, selector/index, type
Included modules: index, util
```

So @olsonpm's command should look like this:

```
npm run bundle -- --include=selector/index,array,event/index
```

Let me know if things work for you! I'll update the docs shortly.

**Comment by olsonpm** [comment]
I'll give it a go sometime this week.  Thanks much for the response

**Comment by jimasun** [comment]
Thanks for updating the instructions. I haven't tested it yet, as I am quite satisfied with the node script.

PS. Something happened with the api documentation. It seems that the [doc page](https://domtastic.js.org/doc/) only shows the `BaseClass`.

Thanks!

**Comment by olsonpm** [comment]
Tested just now - works great.  Much appreciated @webpro
