### ISSUE TITLE
Element API is breaking Isomorphic Apps

### ISSUE THREAD

**Issue by devmarco** [webpro/DOMtastic#39]
I have an isomorphic application, and today I tried to replace Jquery by DOMtastic, but one of the files, most specific `closest.js` is breaking the application, because it is using the new `Element` dom API. See the attached image below.

<img width="1066" alt="screen shot 2016-08-03 at 5 29 45 pm" src="https://cloud.githubusercontent.com/assets/2750520/17381036/6a37cc3c-59a0-11e6-95bd-0c7c27dd60c4.png">

**Comment by webpro** [comment]
Thanks @devmarco, I'm happy to look into this, but I would like to have some way to reproduce this (I can imagine running into more issues like this). Do you have a test case or something I can work with?

**Comment by olsonpm** [comment]
I've been working with a couple isomorphic side-projects and haven't ran into this issue.  I'm assuming @devmarco is triggering a domtastic function on the server-side without meaning to, and the 10-frame stacktrace certainly isn't enough to find the presumed offending file.

**Comment by webpro** [comment]
Thanks for your feedback, @olsonpm. I remember myself including DOMtastic in a Node environment without problems. If anyone has any issues, feel free to discuss. I'm going to close this issue as it's old, and there was no response from topic starter.
