### ISSUE TITLE
data(key) might be "broken" or misleading

### ISSUE THREAD

**Issue by jimasun** [webpro/DOMtastic#40]
I'm not sure if it does what it is intended to do but from what I've understood from the source code, `.data(key)` only returns values that have already been set a priori.

It is misleading since all the `jQuery` references made in the introduction of this toolbox. I was expecting `.data(key)` to return values from `.dataset[]` standard `JS` node property.

The solution might be as simple as changing the value of this `var DATAKEYPROP = '__DOMTASTIC_DATA__';` to `'dataset'`

Well, I'm sure you had some good thought at it when you wrote it. What was the reason?

Thank you

**Comment by webpro** [comment]
Hi @jimasun, thanks for your feedback, I appreciate it. The reason for not using `dataset` initially was mostly browser compatibility. But I agree using `dataset` is indeed better, with the current solution as a fallback.

I'm happy to look into a PR you would submit, or I'll work on it myself in a few days.

**Comment by webpro** [comment]
Once I'll get BrowserStack running, `data()` (using `dataset`) will be in the next release (it's in the master branch if you want to try it).
