### ISSUE TITLE
Why does .on return an integer as the second argument in the callback?

### ISSUE THREAD

**Issue by matt3224** [webpro/DOMtastic#44]
See my pen: http://codepen.io/matt3224/pen/KgJWaR?editors=1010

What is this mystery integer and why is it default? I have no use for such a thing and it means every time I use .on I need to account for this when creating my arguments and when calling the function.

If someone could clear that up for me it would be greatly appreciated, domtastic is pretty great so far!

**Comment by webpro** [comment]
Hi @matt3224, it is kind of mysterious indeed. For some mouse events, the `event.detail` property represents the *mouse count*: https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail

This is the second argument that DOMtastic also passes to your event handler, as you found out.

For custom events however, this is data that can be passed when triggering events:

```
const reusableClickFunction = function(event, detail){
  event.preventDefault();
  console.log(event.detail === detail, detail, event.detail);
};

$(document).on('click', reusableClickFunction);

$(document).on('custom', reusableClickFunction);

$('a').trigger('click', {foo:1});

$('a').trigger('custom', {foo:1});
```

I'll take a look at how I can at least improve the docs on this.

**Comment by matt3224** [comment]
Is there no way to switch that off or remove it? For example here's a snippet from something i'm working on; it is a method and a couple of events from a modal component I have. You can see I am having to provide some value as the second argument and define it in my function which is less the ideal as 99/100 times I will not be using the click count.

```javascript
/*--------------------------------------------------*\
	#CLOSE A MODAL
\*--------------------------------------------------*/

_this.close = function(event, length, element = this) {
    
    event.preventDefault();
    
    if ( $('.modal--visible').length === 1 ) {
    
        $('body').removeClass('locked');
    }
    
    $(element).closest('.modal').removeClass('modal--visible');
};


$(document).on('click', '.js-modal--close', _this.close);


$(document).on('click', '.modal', function(event) {
    
    if ( $(this).hasClass('modal') && event.target === this ) {
    
        _this.close(event, 1, this);
    }
});
```

**Comment by webpro** [comment]
I've eventually decided too make a patch release. Can you please check out v0.12.3?

**Comment by matt3224** [comment]
Okay so i get an error on bundle, it does complete but domtastic is 3kb lighter than the bundle from your cdn and has a problem with `$`

Check this screenshot: 
![screen shot 2016-10-25 at 22 53 26](https://cloud.githubusercontent.com/assets/2401925/19705732/02471b08-9b06-11e6-93d4-60826365ee14.png)

**Comment by webpro** [comment]
* The build is smaller, but it still passes all tests (the minification goes a bit different now).
* You can use the pre-built `dist/domtastic.js` (or `domtastic.min.js`).

What is the problem with `$`? Just tried it, and it's globally available if I just insert the `<script>` tag, and I can also `require` it:

```
❯ node
> var $ = require('domtastic');
undefined
> $.version
'0.12.3'
```

If you can share your setup I'm happy to look into it.

**Comment by matt3224** [comment]
I use CodeKit to handle my transpiling and minification. CK doesn't yet support converting es6 modules to es5 using rollup so for now i'm including your bundle in my build.

You don't currently offer a dist folder in the repo so I thought I needed to bundle it myself which is what led me to the issue above.

If I include what rollup outputs into dist I get the following error: `TypeError: undefined is not an object (evaluating 'global.$ = factory()')`

Thanks for helping me out on this, much appreciated!

**Comment by webpro** [comment]
When installing from npm, the `dist` folder now contains the bundle. Does CK install using Bower or Github? But indeed, if it's not coming from npm, there's no transpiled bundle, so you'd need to manually bundle it.

Looks like the `this` (`global`) variable is not at the top level anymore (probably gets wrapped by CK or something). My first guess is that the rollup UMD output has changed somehow recently and that it was more bulletproof before (since 0.12.1 is different).

**Comment by matt3224** [comment]
HI Lars,

Here's a rundown of my process to include DOMtastic:

1. Download the repo via zip
2. Run `npm install` via terminal
3. Run `npm run bundle`
4. Copy domtastic.min.js to my project folder
5. Use CodeKits' js concatenation to combine domtastic with my project js, putting DOMtastic first

I have re-bundled (which works ok now), placed the file in my build and I get that error on page load. If I switch back to 0.12 (from the cdn) it works as expected.

I hope that helps

**Comment by webpro** [comment]
Your environment is doing something different than mine:

```
❯ npm run bundle

> domtastic@0.12.3 bundle /Users/lars/Projects/tmp/DOMtastic-master
> rollup -c

The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
```

The difference in your situation is that it renders an `undefined` on the last line (and `this` for me):

```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global.$ = factory());
}(this, (function () { 'use strict';
```

Is the `domtastis.js` you copy to your project folder the same as mine? Does `this` get rewritten to `undefined` by CodeKit?

(Also see: https://www.google.nl/search?q=this+keyword+is+equivalent+to+undefined+at+the+top+level+of+an+ES+module)

**Comment by matt3224** [comment]
Oh no! I think you may be right, I have separated DOMtastic and included it as its own script file and the error has gone. CodeKit must be doing something it shouldn't, let me file a bug report with Bryan and see what he says. I'll keep you posted!

**Comment by webpro** [comment]
OK @matt3224, I'm going to close this issue (it was actually about the `on` method anyway).

**Comment by matt3224** [comment]
That's cool, i did some more testing and its CodeKits implementation of babel mixed with file concatenation that's causing the issue, as you suggested. Thanks for all your help, really appreciate it!

**Comment by webpro** [comment]
OK @matt3224, feel free to open new issues if you have anything else.
