### ISSUE TITLE
How to deal with 3rd-party plugins that use jQuery in a CMS such as WordPress

### ISSUE THREAD

**Issue by matt3224** [webpro/DOMtastic#45]
Hey Lars,

I just wondered how best to deal with such madness. We use WordPress a lot for client sites and quite often third-party plugins will use jQuery by default which as you can imagine is problematic when we are using DOMtastic for the theme.

Do you have any words of wisdom on this subject?

Thanks,
Matt

**Comment by webpro** [comment]
You can use [$.noConflict()](https://domtastic.js.org/doc/#noconflict) (jQuery has it as well). Does that help?

**Comment by matt3224** [comment]
Yes I think I could use noConflict, I may not need to but probably should, even if it is just to return the original $ state. I will be loading domtastic first in all cases so it isn't a massive issue I am just working out the best way to structure our in-house front-end framework.

//Here's some backstory...

I did have it all in pure ES6/2015 (transpiling for IE11) and that felt nice but I found myself polyfilling things and the way you add multi-element events is tedious. Then I thought maybe just use domtastic as a bootstrap as its fast and everyone understands the jQuery style syntax it uses. However I neglected to take into consideration WP plugins and their overuse of jQuery.

So I now need to decide how to proceed, I can go back to pure js and polyfill a few things, using domtastic only at the app level, or I can continue to use domtastic at the framework level and allow for jquery in my iife's or use noconflict. There are pro's and con's of each so it's tricky to decide.

Anyway I'll close this issue and be sure to send you some more from the diaries of an indecisive developer 😉

Thanks,

**Comment by webpro** [comment]
> I found myself polyfilling things and the way you add multi-element events is tedious

What do you mean by this? If you have questions, feedback or ideas on how to improve things, I'm happy to discuss in another PR if you want to.

**Comment by matt3224** [comment]
I just mean in pure js

**Comment by matt3224** [comment]
I think domtastic works wonderfully well
