### ISSUE TITLE
.each works differently to jQuery

### ISSUE THREAD

**Issue by matt3224** [webpro/DOMtastic#47]
I have edited the initial question after I found this `forEach (alias: each)` however it seems to work differently to the implementation. I would like to do this for example:

```
$('.tabs').each(function(){
   $(this).find('.tab').text('hello'); 
});
```

It would be great to use DOMtastic as a super fast interchangeable dom library for all dom traversal tasks such as this. It seems like this is the goal afterall

Thanks

**Comment by webpro** [comment]
The goal is indeed to be an alternative to jQuery. However, the callback interface with the `index` as first argument is counter-intuitive. So this is how DOMtastic works:

```
$('.tabs').each(function(element, index){
   $(element).find('.tab').text('hello'); 
});
```

However, you can [make a custom build](https://github.com/webpro/DOMtastic#jquery-compatibility) to match jQuery's style using `npm run build -- --jquery-compat`:

```
$('.tabs').each(function(index, element){
   $(element).find('.tab').text('hello'); 
});
```

Are you saying that `this` doesn't equal `element`? The unit tests seem tell me something different...

**Comment by matt3224** [comment]
Ah ha! I overlooked the jQuery compatibility mode, thanks!
