### ISSUE TITLE
Benchmark page is dead

### ISSUE THREAD

**Issue by gsouf** [webpro/DOMtastic#51]
Hi, the benchmark page on the website has passed away :'( 

https://domtastic.js.org/benchmark/

**Comment by webpro** [comment]
Thanks, @gsouf. Actually I was waiting to release a new version quickly which will restore this. I'll do it soon!

**Comment by webpro** [comment]
And they're back :-)

**Comment by gsouf** [comment]
:tada:  Benchmarks look very promising
