### ISSUE TITLE
Determine if an object is a domtastic instance

### ISSUE THREAD

**Issue by gsouf** [webpro/DOMtastic#52]
Hi, that's a question before being an issue, but I couldnt find a best place to ask for it.

I'm trying to determine if an object is an instance of domtastic or not.

I ended up with this workaround: 

```js
typeof element == 'object' && element.constructor.name == 'Wrapper'
```

But ``Wrapper`` class name is not unique to domtastic, and, though the risk is really minor, it could lead to an error.
Is there a better way to do?

In jquery I would do this:

```js
typeof element == 'object' && element instanceof jQuery
```
Thanks

**Comment by webpro** [comment]
I can probably make `$.name === 'domtastic'`, but for now you could use your workaround, or alternatively `$.fn.find === element.find`.

**Comment by webpro** [comment]
To see if `selector` is an instance of `$` you can already also use this:

```
const element = $(document);
element === $(element); // true
```

I will also add the following function names to the selector function and the constructor:

```
$.name; // 'domtastic'

const element = $(selector);
element.constructor.name; // 'DOMtastic'
```
