### ISSUE TITLE
first

### ISSUE THREAD

**Issue by gsouf** [webpro/DOMtastic#53]
Hi,

A minor but life saver feature is missing (in my opinion) in domtastic.

It's ``$element.first()`` I know it's the same as ``.eq(0)`` however its implementation is very lightweight and it can fill a compatibility issue with jQuery.

What do you think ?

**Comment by webpro** [comment]
Good idea. Would you like to open a PR for this?

**Comment by gsouf** [comment]
@webpro would also like to implement ``.last`` ?

**Comment by webpro** [comment]
Thanks, @gsouf! I'm not looking for 100% replacement of jQuery, although it's hard to draw a line. Btw, perhaps the easiest way to do `.last()` is `.slice(-1)`.

**Comment by gsouf** [comment]
Sure, I dont know people habits, but in my case I almost never use .last, but I use .first very often (and that makes replacement of jquery with dommtastic much mmore comfortable), that's why I just asked for .first at a first glance. Let's see if some people need it at some point. Anyway the library can be extended easily.

**Comment by webpro** [comment]
Yes, extending `$.fn` is also possible.

**Comment by gsouf** [comment]
Hi @webpro, are you planning a bump soon for this feature?

**Comment by webpro** [comment]
Apologies, I totally forgot! Just release [v0.14.0](https://github.com/webpro/DOMtastic/releases/tag/0.14.0)

**Comment by gsouf** [comment]
Thank you :)
