### ISSUE TITLE
Event on with '>' selector not working

### ISSUE THREAD

**Issue by Wikiki** [webpro/DOMtastic#56]
Hi,

first of all, very good work ;-)

I found an  issue with the event on.
If I try to create this kind of event:
```
$('.div').on( 'click', '>', function() {
alert( 'BLIP' );
});
```

which is working well with JQuery (see JSFiddle [here](https://jsfiddle.net/c6up267s/) ), I get the following error with DOMtastic:
```
SyntaxError: '>' is not a valid selector
TypeError: node.closest is not a function
```

Same problem with selectors like `$( '> .title' )`

Do you have any idea how to fix that ?

Regards,

**Comment by webpro** [comment]
Hi @Wikiki. The error message is clear: you can only use valid selectors, see e.g. https://developer.mozilla.org/nl/docs/Web/CSS/CSS_Selectors.

You could use alternatives like this:

```
$('ul').on( 'click', 'ul > li', handler);
$('ul').children().on( 'click', handler);
```

Does that help?

**Comment by Wikiki** [comment]
Hi,

Thanks for your answer.
I agree with you regarding the message. It's clear but I'm trying to write a drag' n drop module using your library and for it I don't know in advance the parent node. (It will be determined during the module instanciation like `$( '#section' ).droppable( { items: ">" } );`
For example I want to be able to run the following code:

`$element.on( 'dragenter', settings.items, onDragEnter );`

where settigns.items can be (for example):
```
- ">"
- ".myDiv >"
- ".myDiv > mysubDiv1 >"
- ...
```

Do you have any idea how I could do that ?

Regards,

**Comment by webpro** [comment]
Getting a sense of what you're after. Can you share some more code I can try?

**Comment by Wikiki** [comment]
Hi,

I put some code here: [https://github.com/Wikiki/dragndrop](https://github.com/Wikiki/dragndrop) for you.

Regards

**Comment by webpro** [comment]
Sorry, but it looks like dependencies are missing, nor is it code I can try and run in my browser (perhaps with some build command?) :-)

**Comment by Wikiki** [comment]
Sorry, my bad.

I put the correct version with you library on my github. I've created a folder "dnd" within src dir and included my sources into index.js so you just have to build the source to test.

Regards.

**Comment by webpro** [comment]
Sorry, but I'm going to close this issue. The original question is, hopefully, answered adequately. If there are any specific questions or remarks about this library, I'm happy to investigate or discuss.

Btw, I do see Zepto has support for this (https://github.com/madrobby/zepto/blob/97de41256d3c511ddb06e6d36d9a16388e9d2da5/src/selector.js#L61-L67), so I might consider and add something similar as well.
