### ISSUE TITLE
Use with webpack & ProvidePlugin

### ISSUE THREAD

**Issue by darbymanning** [webpro/DOMtastic#70]
I realise this is really a webpack configuration issue, but I thought you might be able to help ...

I'm using it to load domtastic automagically when $ or jQuery is used. Here's what I have in webpack.config.js under plugins:

```
new webpack.ProvidePlugin({
    $: path.join(__dirname, 'node_modules', 'domtastic'),
    jQuery: path.join(__dirname, 'node_modules', 'domtastic')
})
```

This works great on my main bundle.js file if I use `$` or `jQuery`, it requires it as expected. However if I import any other .js as a partial in bundle.js which uses $ it fails to require domtastic. So for example:

*bundle.js*
`import "./partials/script1.js";`

*partials/script1.js*
`console.log($);`

This results in: `Uncaught TypeError: $ is not a function`

Any ideas on how I can get this working with partials without manually requiring domtastic on each partial that uses it?

**Comment by webpro** [comment]
You should `import $ from 'domtastic'`. I understand you don't want to, but that's how it works. Not sure how to work with globals. Maybe there's a Webpack plugin or something that automatically inserts the `import/require` statements for you. You could also just always load $/jQuery upfront (script tag/CDN) to make sure it's available globally.
