### ISSUE TITLE
$.closest maximum callstack 

### ISSUE THREAD

**Issue by gsouf** [webpro/DOMtastic#71]
Hi,

When using $.closest with an object whose the required grand parent is very far away, the javascript engine will stop the execution of the closest method.

**Comment by webpro** [comment]
How far is "very far away", in number of parent nodes? Do you have a test case I can try?

**Comment by gsouf** [comment]
Not so much actually: something like 12, but I think the issue is something else because according to this fiddle there is no issue: https://jsfiddle.net/278th7cm/
Investigating now

**Comment by gsouf** [comment]
Well, that was my fault, calling $(a).closest when a was not a valid selector. I was fooled by the fact that closest might actually cause this issue due to its recursive nature.

**Comment by webpro** [comment]
I'm glad you found the issue :-)
