### ISSUE TITLE
$.data doesn't work when hyphen is used

### ISSUE THREAD

**Issue by nickngqs** [webpro/DOMtastic#96]
This will not work
```pug
div(data-animal-type='dragon')
```
```js
$('div').data('animal-type'); // undefined
```

This will work
```pug
div(data-animaltype='dragon')
```
```js
$('div').data(animaltype); // dragon
```

I think animal-type should work since we see alot of hyphens in HTML documents and is in the spec as well

**Comment by webpro** [comment]
Thanks @nickngqs, you're absolutely right. This has been fixed and [released as v0.15.5](https://github.com/webpro/DOMtastic/releases/tag/0.15.5).
